Login pages
ovisannn/disspace-UI pull request #12
Opened 2021-12-23 14:14 UTC by ovisannn

2021-12-23 14:15 UTC, ovisannn commented
![image](https://user-images.githubusercontent.com/57137490/147252358-678746d9-a6a0-439c-9c82-53fe53806e77.png)

![image](https://user-images.githubusercontent.com/57137490/147252403-d05a6fb3-5ec8-4662-969b-9de26b36e501.png)

2021-12-23 14:16 UTC, ovisannn commented
navbar nya masih belum aku fix ges.. rencana mau aku rework

2021-12-24 04:15 UTC, geraldioeres requested changes
Gini kalau dilayarku mas, tapi kalau dinaikin jadi 85 atau 90 aman.

![login](https://user-images.githubusercontent.com/85932614/147315421-acf6cce3-7e53-4cce-9683-cf69df3a439f.JPG)

2021-12-24 04:15 UTC, geraldioeres commented on pages/login/index.jsx
> +        <div className="border-2 border-orange rounded-lg w-80 py-10 shadow flex flex-col">
Saranku bagian w-80 nya dinaikin dikit mas jadi 85 atau 90. Soalnya kalau ukuran layarnya kayak punyaku dia kepotong gitu.

2021-12-24 09:23 UTC, geraldioeres approved these changes
Wokeh aman

2021-12-27 08:21 UTC, merged